package main

import (
	"bufio"
	"fmt"
	"sort"
	"strings"

	"go.imnhan.com/s4g/writablefs"
)

// Write list of files generated by s4g
func WriteManifest(fsys writablefs.FS, files map[string]bool) {
	lines := make([]string, 0, len(files))
	for path := range files {
		lines = append(lines, path)
	}
	sort.Strings(lines)
	fsys.WriteFile(ManifestPath, []byte(strings.Join(lines, "\n")))
}

// Read list of old generated files from the manifest file,
// then delete those that are no longer relevant.
func DeleteOldGeneratedFiles(fsys writablefs.FS, currentFiles map[string]bool) {
	oldFiles := readManifest(fsys)
	numRemovals := 0

	for path := range oldFiles {
		_, ok := currentFiles[path]
		if !ok {
			fsys.RemoveAll(path)
			numRemovals += 1
			fmt.Println("Removed", path)
		}
	}

	if numRemovals > 0 {
		fmt.Printf("Removed %d outdated files\n", numRemovals)
	}
}

func readManifest(fsys writablefs.FS) map[string]bool {
	result := make(map[string]bool)

	f, err := fsys.Open(ManifestPath)
	if err != nil {
		return result
	}
	defer f.Close()

	s := bufio.NewScanner(f)
	for s.Scan() {
		result[s.Text()] = true
	}
	return result
}
